ALTER TABLE images ADD COLUMN priority INTEGER NOT NULL DEFAULT 1;
ALTER TABLE images ADD COLUMN duration_seconds INTEGER NOT NULL DEFAULT 10;
ALTER TABLE images ADD COLUMN total_cost INTEGER NOT NULL DEFAULT 0;
