ALTER TABLE images ADD COLUMN is_info_message BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE images ADD COLUMN is_flash_mode BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE images ADD COLUMN message_text TEXT;
