name: Test and Coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up JDK 25
        uses: actions/setup-java@v2
        with:
          java-version: '25'
          
      - name: Run tests and generate JaCoCo report
        run: mvn clean test
        
      - name: Deploy JaCoCo report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site/jacoco
          publish_branch: gh-pages
